---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: one-eyed-minion
  labels:
    serviceType: one-eyed-minion
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: one-eyed-minion
      labels:
        serviceType: one-eyed-minion
    spec:
      containers:
        - name: one-eyed-minion
          image: sptingbootregistry.azurecr.io/gs-spring-boot-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: SPRING_APPLICATION_NAME
            value: "one-eyed-minion"
      imagePullSecrets:
          - name: sptingbootregistry
---
apiVersion: v1
kind: Service
metadata:
  name: one-eyed-minion
  namespace: default
  annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: one-eyed-minion
    serviceType: one-eyed-minion
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: two-eyed-minion
  labels:
    serviceType: two-eyed-minion
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: two-eyed-minion
      labels:
        serviceType: two-eyed-minion
    spec:
      containers:
        - name: two-eyed-minion
          image: sptingbootregistry.azurecr.io/gs-spring-boot-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: SPRING_APPLICATION_NAME
            value: "two-eyed-minion"
---
apiVersion: v1
kind: Service
metadata:
  name: two-eyed-minion-entrypoint
  namespace: default
spec:
  selector:
    serviceType: two-eyed-minion
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sad-minion
  labels:
    serviceType: sad-minion
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: sad-minion
      labels:
        serviceType: sad-minion
    spec:
      containers:
        - name: sad-minion
          image: sptingbootregistry.azurecr.io/gs-spring-boot-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: SPRING_APPLICATION_NAME
            value: "sad-minion"
---
apiVersion: v1
kind: Service
metadata:
  name: sad-minion-entrypoint
  namespace: default
spec:
  selector:
    serviceType: sad-minion
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: happy-minion
  labels:
    serviceType: happy-minion
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: happy-minion
      labels:
        serviceType: happy-minion
    spec:
      containers:
        - name: happy-minion
          image: sptingbootregistry.azurecr.io/gs-spring-boot-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: SPRING_APPLICATION_NAME
            value: "happy-minion"
---
apiVersion: v1
kind: Service
metadata:
  name: happy-minion-entrypoint
  namespace: default
spec:
  selector:
    serviceType: happy-minion
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30083
  type: NodePort
